# basic settings
title: "Ovee - CV / Resume Jekyll Theme"
email: "wahed.ovee@gmail.com"
description: "Jekyll Resume / CV / vCard template"
author: "Ovee"
baseurl: "oveew.github.io/blog" # the subpath of your site, e.g. /blog
url: "https://oveew.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%b %d, %Y"

# paginations & permalinks
paginate: 4
paginate_path: "/page:num/"
permalink: pretty
			
